name: Build APK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Java17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Flutter
        uses: Subosito/Flutter-action@v2
        with:
          flutter-version: 3.22.0

      - name: 修复项目结构
        run: flutter create .

      - name: 依赖
        run: flutter pub get

      - name: 打包APK
        run: flutter build apk --release

      - name: 下载安装包
        uses: actions/upload-artifact@v4
        with:
          name: AgentHub-APK
          path: build/app/outputs/flutter-apk/app-release.apk
